version: 2.1
orbs:
  slack: circleci/slack@3.4.2

executors:
  tap_tester:
    docker:
      - image: 218546966473.dkr.ecr.us-east-1.amazonaws.com/circle-ci:stitch-tap-tester
jobs:
  ensure_env:
    executor: tap_tester
    steps:
      - checkout
      - run:
          name: 'Setup virtual env'
          command: |
            python3 -m venv /usr/local/share/virtualenvs/tap-hubspot/
            source /usr/local/share/virtualenvs/tap-hubspot/bin/activate
            pip install -U 'pip<19.2' 'setuptools<51.0.0'
            pip install .[dev]
      - persist_to_workspace:
          root: /usr/local/share/virtualenvs/
          paths:
            - tap-hubspot
  build:
    executor: tap_tester
    steps:
      - checkout
      - attach_workspace:
          at: /usr/local/share/virtualenvs
      - run:
          name: 'pylint'
          command: |
            source /usr/local/share/virtualenvs/tap-hubspot/bin/activate
            pylint tap_hubspot -d C,R,W
      - run:
          name: 'Unit Tests'
          command: |
            source /usr/local/share/virtualenvs/tap-hubspot/bin/activate
            nosetests tap_hubspot/tests
      - run:
          name: 'JSON Validator'
          command: |
            source /usr/local/share/virtualenvs/tap-tester/bin/activate
            stitch-validate-json tap_hubspot/schemas/*.json
  integration_test:
    parameters:
      test_command:
        type: string
    executor: tap_tester
    steps:
      - checkout
      - attach_workspace:
          at: /usr/local/share/virtualenvs
      - add_ssh_keys
      - run:
          name: 'Integration Tests'
          command: |
            aws s3 cp s3://com-stitchdata-dev-deployment-assets/environments/tap-tester/tap_tester_sandbox dev_env.sh
            source dev_env.sh
            source /usr/local/share/virtualenvs/tap-tester/bin/activate
            << parameters.test_command >>
      - slack/notify-on-failure:
          only_for_branches: master

workflows:
  version: 2
  commit: &commit_jobs
    jobs:
      - ensure_env:
          context: circleci-user
      - build:
          context: circleci-user
          requires:
            - ensure_env
      - integration_test:
          name: "Discovery Test"
          context: circleci-user
          test_command: |-
            run-test --tap=${CIRCLE_PROJECT_REPONAME} tests/test_hubspot_discovery.py
          requires:
            - build
      - integration_test:
          name: "Automatic Fields Test"
          context: circleci-user
          test_command: |-
            run-test --tap=${CIRCLE_PROJECT_REPONAME} tests/test_hubspot_automatic_fields_test.py
          requires:
            - build
      - integration_test:
          name: "Child Streams Test"
          context: circleci-user
          test_command: |-
            run-test --tap=${CIRCLE_PROJECT_REPONAME} tests/test_hubspot_child_stream_only.py
          requires:
            - "Discovery Test"
            - "Automatic Fields Test"
      - integration_test:
          name: "Start Date Test"
          context: circleci-user
          test_command: |-
            run-test --tap=${CIRCLE_PROJECT_REPONAME} tests/test_hubspot_start_date_test.py
          requires:
            - "Discovery Test"
            - "Automatic Fields Test"
      - integration_test:
          name: "All Fields Test"
          context: circleci-user
          test_command: |-
            run-test --tap=${CIRCLE_PROJECT_REPONAME} tests/test_hubspot_all_fields_test.py
          requires:
            - "Start Date Test"
      - integration_test:
          name: "Pagination Test"
          context: circleci-user
          test_command: |-
            run-test --tap=${CIRCLE_PROJECT_REPONAME} tests/test_hubspot_pagination_test.py
          requires:
            - "All Fields Test"
  build_daily:
    <<: *commit_jobs
    triggers:
      - schedule:
          cron: "0 6 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build:
          context: circleci-user
