version: 2
jobs:
  build:
    docker:
      - image: 218546966473.dkr.ecr.us-east-1.amazonaws.com/circle-ci:tap-tester-v4
    steps:
      - checkout
      - run:
          name: 'Setup virtual env'
          command: |
            python3 -m venv /usr/local/share/virtualenvs/tap-hubspot/
            source /usr/local/share/virtualenvs/tap-hubspot/bin/activate
            pip install -U 'pip<19.2' setuptools
            pip install .[dev]
      - run:
          name: 'pylint'
          command: |
            source /usr/local/share/virtualenvs/tap-hubspot/bin/activate
            pylint tap_hubspot -d C,R,W
      - run:
          name: 'Unit Tests'
          command: |
            source /usr/local/share/virtualenvs/tap-hubspot/bin/activate
            nosetests tap_hubspot/tests
      - run:
          name: 'JSON Validator'
          command: |
            source /usr/local/share/virtualenvs/tap-tester/bin/activate
            stitch-validate-json /usr/local/share/virtualenvs/tap-hubspot/lib/python3.5/site-packages/tap_hubspot/schemas/*.json
      - add_ssh_keys
      - run:
          name: 'Integration Tests'
          command: |
            aws s3 cp s3://com-stitchdata-dev-deployment-assets/environments/tap-tester/sandbox dev_env.sh
            source dev_env.sh
            source /usr/local/share/virtualenvs/tap-tester/bin/activate
            run-test --tap=tap-hubspot \
                     --target=target-stitch \
                     --orchestrator=stitch-orchestrator \
                     --email=harrison+sandboxtest@stitchdata.com \
                     --password=$SANDBOX_PASSWORD \
                     --client-id=50 \
                     tests
workflows:
  version: 2
  commit:
    jobs:
      - build:
          context: circleci-user
  build_daily:
    triggers:
      - schedule:
          cron: "0 17 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build:
          context: circleci-user
